---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: env-share-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard-rwo	

---
apiVersion: batch/v1
kind: Job
metadata:
  name: pv-init-job-default
  labels:
    app: pv-init-job
spec:
  backoffLimit: 4  # Pod失敗時的重試次數
  ttlSecondsAfterFinished: 60  # Pod完成後60秒自動刪除
  template:
    metadata:
      labels:
        app: pv-init-job
    spec:
      restartPolicy: Never
      containers:
        - name: pv-init
          image: alpine
          command: ["sh", "-c", "echo 'Initializing PV'; sleep 10"]  # 印一條init訊息並等待10秒，然後完成該pod(非啟動)
          volumeMounts:  # 綁定到容器內的位置，設定任何 volumeMounts 都需要在下面的 volumes 有定義
            - mountPath: /usr
              name: env-share-vol
      volumes:
        - name: env-share-vol
          persistentVolumeClaim:
            claimName: env-share-pvc